#!/bin/sh

export PROJECT=Gameye/match-api-spec
export BRANCH=$(git branch --show-current)

set +e # continue on error

grep --no-messages --silent ^github\.com, ~/.ssh/known_hosts
if [ $? -eq 0 ]
then
    export UPSTREAM_URL=git@github.com:$PROJECT.git
else 
    export UPSTREAM_URL=https://github.com/$PROJECT.git
fi

set -e # Exit immediately if a command exits with a non-zero status.

git pull --no-rebase $UPSTREAM_URL $BRANCH:$BRANCH
git push origin $BRANCH:$BRANCH
